Add constituency model
devcongress/elections-api pull request #33
Opened 2017-10-29 12:11 UTC by 0sc

This PR adds the constituency model

2017-10-29 14:00 UTC, silentworks commented
Good job @0sc. I cannot merge this because the build failed, there error is:

```
test/models/constituency_test.rb:1:9: C: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
require 'test_helper'
```

Please fix and update your PR and I will get it merged in.

2017-10-29 19:23 UTC, 0sc commented
Ahh, good catch. I'll make the update.

2017-10-30 20:04 UTC, yawboakye requested changes

2017-10-30 20:04 UTC, yawboakye commented on db/migrate/20171009134732_create_constituencies.rb
> +    create_table :constituencies do |t|
Use `uuid` for constituency id

2017-10-31 16:21 UTC, 0sc commented on db/migrate/20171009134732_create_constituencies.rb
> +    create_table :constituencies do |t|
Done @yawboakye

2017-11-04 09:05 UTC, yawboakye approved these changes
LGTM cc/ @bubunyo can you have another pass? Thank you.

2017-11-04 12:51 UTC, bubunyo approved these changes
Seems legit.

2017-11-04 18:39 UTC, merged